name: Metrics

on:
  schedule: [{cron: "0 2 * * *"}]
  workflow_dispatch:
  push: {branches: ["main", "master"]}

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - name: Isometric calendar (full year)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Follow-up issues & pull requests
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_followup_indepth: yes
